In [7]:
import numpy as np

In [27]:
a=np.random.randint(30,99,(7,8))

In [29]:
a

array([[78, 40, 90, 89, 89, 74, 82, 51],
       [92, 82, 88, 91, 63, 75, 54, 48],
       [85, 57, 92, 48, 92, 86, 72, 97],
       [88, 37, 48, 95, 49, 49, 32, 62],
       [65, 63, 89, 51, 50, 33, 37, 50],
       [43, 46, 70, 44, 59, 30, 78, 72],
       [77, 34, 36, 55, 67, 79, 53, 35]])

In [31]:
np.random.seed(55)
a=np.random.randint(30,99,20)
a

array([56, 69, 59, 91, 85, 67, 63, 84, 65, 76, 91, 42, 54, 61, 81, 30, 85,
       92, 73, 79])

In [33]:
a.shape

(20,)

In [ ]:
array[row_start: row_end : row_step , col_start: col_end:col_step]

In [35]:
b=np.random.randint(20,80,(8,9))
b

array([[44, 68, 34, 76, 30, 79, 79, 48, 61],
       [64, 44, 72, 49, 64, 41, 33, 72, 61],
       [78, 53, 65, 44, 38, 36, 65, 75, 47],
       [38, 76, 62, 52, 73, 30, 74, 23, 44],
       [78, 27, 38, 21, 39, 65, 73, 50, 39],
       [30, 45, 22, 44, 52, 33, 55, 31, 54],
       [35, 53, 62, 54, 68, 79, 41, 40, 23],
       [27, 40, 33, 54, 36, 60, 39, 46, 34]])

In [37]:
b.shape

(8, 9)

In [39]:
b[1:5,1:6]

array([[44, 72, 49, 64, 41],
       [53, 65, 44, 38, 36],
       [76, 62, 52, 73, 30],
       [27, 38, 21, 39, 65]])

In [47]:
import pandas as pd

In [55]:
k=[[4,7],[2,9],[7,3],[90,50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [79]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [81]:
t.ndim

2

In [83]:
pd.Series(t)

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 2) instead

In [85]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2   7   3
3  90  50

In [87]:
pd.DataFrame(t,columns=['name','sub'],index=[289,290,291,292])

name  sub
289     4    7
290     2    9
291     7    3
292    90   50