In [36]:
import pandas as pd
import numpy as np 

In [37]:
movies_df=pd.read_csv(r"C:\Users\RITHVIK REDDY\OneDrive\Documents\Movie.csv")

In [38]:
movies_df.shape

(8992, 3)

In [39]:
movies_df.head()

userId             movie  rating
0       3  Toy Story (1995)     4.0
1       6  Toy Story (1995)     5.0
2       8  Toy Story (1995)     4.0
3      10  Toy Story (1995)     4.0
4      11  Toy Story (1995)     4.5

In [40]:
movies_df[movies_df['userId']==6]

userId                    movie  rating
1          6         Toy Story (1995)     5.0
3725       6  Grumpier Old Men (1995)     3.0
6464       6           Sabrina (1995)     5.0

In [41]:
len(movies_df.userId.unique())

4081

In [42]:
len(movies_df.movie.unique())

10

In [43]:
movies_df.movie.unique()

array(['Toy Story (1995)', 'Jumanji (1995)', 'Grumpier Old Men (1995)',
       'Waiting to Exhale (1995)', 'Father of the Bride Part II (1995)',
       'Heat (1995)', 'Sabrina (1995)', 'Tom and Huck (1995)',
       'Sudden Death (1995)', 'GoldenEye (1995)'], dtype=object)

In [58]:
user_movies_df=movies_df.pivot(index='userId',
                               columns='movie',
                               values='rating').reset_index(drop=True)  

In [59]:
user_movies_df

movie  Father of the Bride Part II (1995)  GoldenEye (1995)  \
0                                     NaN               NaN   
1                                     NaN               NaN   
2                                     NaN               NaN   
3                                     NaN               4.0   
4                                     NaN               NaN   
...                                   ...               ...   
4076                                  4.0               NaN   
4077                                  3.5               NaN   
4078                                  NaN               3.0   
4079                                  NaN               NaN   
4080                                  NaN               NaN   

movie  Grumpier Old Men (1995)  Heat (1995)  Jumanji (1995)  Sabrina (1995)  \
0                          NaN          NaN             3.5             NaN   
1                          4.0          NaN             NaN             NaN   
2                          NaN          NaN             NaN             NaN   
3                          NaN          3.0             NaN             NaN   
4                          NaN          NaN             3.0             NaN   
...                        ...          ...             ...             ...   
4076                       NaN          NaN             NaN             NaN   
4077                       NaN          NaN             NaN             NaN   
4078                       4.0          5.0             NaN             3.0   
4079                       NaN          NaN             NaN             NaN   
4080                       NaN          NaN             4.0             4.0   

movie  Sudden Death (1995)  Tom and Huck (1995)  Toy Story (1995)  \
0                      NaN                  NaN               NaN   
1                      NaN                  NaN               NaN   
2                      NaN                  NaN               4.0   
3                      NaN                  NaN               NaN   
4                      NaN                  NaN               NaN   
...                    ...                  ...               ...   
4076                   NaN                  NaN               NaN   
4077                   NaN                  NaN               4.0   
4078                   1.0                  NaN               4.0   
4079                   NaN                  NaN               5.0   
4080                   NaN                  NaN               4.5   

movie  Waiting to Exhale (1995)  
0                           NaN  
1                           NaN  
2                           NaN  
3                           NaN  
4                           NaN  
...                         ...  
4076                        NaN  
4077                        NaN  
4078                        NaN  
4079                        NaN  
4080                        NaN  

[4081 rows x 10 columns]

In [60]:
user_movies_df.index = movies_df.userId.unique()

In [61]:
user_movies_df

movie  Father of the Bride Part II (1995)  GoldenEye (1995)  \
3                                     NaN               NaN   
6                                     NaN               NaN   
8                                     NaN               NaN   
10                                    NaN               4.0   
11                                    NaN               NaN   
...                                   ...               ...   
7044                                  4.0               NaN   
7070                                  3.5               NaN   
7080                                  NaN               3.0   
7087                                  NaN               NaN   
7105                                  NaN               NaN   

movie  Grumpier Old Men (1995)  Heat (1995)  Jumanji (1995)  Sabrina (1995)  \
3                          NaN          NaN             3.5             NaN   
6                          4.0          NaN             NaN             NaN   
8                          NaN          NaN             NaN             NaN   
10                         NaN          3.0             NaN             NaN   
11                         NaN          NaN             3.0             NaN   
...                        ...          ...             ...             ...   
7044                       NaN          NaN             NaN             NaN   
7070                       NaN          NaN             NaN             NaN   
7080                       4.0          5.0             NaN             3.0   
7087                       NaN          NaN             NaN             NaN   
7105                       NaN          NaN             4.0             4.0   

movie  Sudden Death (1995)  Tom and Huck (1995)  Toy Story (1995)  \
3                      NaN                  NaN               NaN   
6                      NaN                  NaN               NaN   
8                      NaN                  NaN               4.0   
10                     NaN                  NaN               NaN   
11                     NaN                  NaN               NaN   
...                    ...                  ...               ...   
7044                   NaN                  NaN               NaN   
7070                   NaN                  NaN               4.0   
7080                   1.0                  NaN               4.0   
7087                   NaN                  NaN               5.0   
7105                   NaN                  NaN               4.5   

movie  Waiting to Exhale (1995)  
3                           NaN  
6                           NaN  
8                           NaN  
10                          NaN  
11                          NaN  
...                         ...  
7044                        NaN  
7070                        NaN  
7080                        NaN  
7087                        NaN  
7105                        NaN  

[4081 rows x 10 columns]

In [62]:
user_movies_df.fillna(0,inplace=True)

In [63]:
user_movies_df

movie  Father of the Bride Part II (1995)  GoldenEye (1995)  \
3                                     0.0               0.0   
6                                     0.0               0.0   
8                                     0.0               0.0   
10                                    0.0               4.0   
11                                    0.0               0.0   
...                                   ...               ...   
7044                                  4.0               0.0   
7070                                  3.5               0.0   
7080                                  0.0               3.0   
7087                                  0.0               0.0   
7105                                  0.0               0.0   

movie  Grumpier Old Men (1995)  Heat (1995)  Jumanji (1995)  Sabrina (1995)  \
3                          0.0          0.0             3.5             0.0   
6                          4.0          0.0             0.0             0.0   
8                          0.0          0.0             0.0             0.0   
10                         0.0          3.0             0.0             0.0   
11                         0.0          0.0             3.0             0.0   
...                        ...          ...             ...             ...   
7044                       0.0          0.0             0.0             0.0   
7070                       0.0          0.0             0.0             0.0   
7080                       4.0          5.0             0.0             3.0   
7087                       0.0          0.0             0.0             0.0   
7105                       0.0          0.0             4.0             4.0   

movie  Sudden Death (1995)  Tom and Huck (1995)  Toy Story (1995)  \
3                      0.0                  0.0               0.0   
6                      0.0                  0.0               0.0   
8                      0.0                  0.0               4.0   
10                     0.0                  0.0               0.0   
11                     0.0                  0.0               0.0   
...                    ...                  ...               ...   
7044                   0.0                  0.0               0.0   
7070                   0.0                  0.0               4.0   
7080                   1.0                  0.0               4.0   
7087                   0.0                  0.0               5.0   
7105                   0.0                  0.0               4.5   

movie  Waiting to Exhale (1995)  
3                           0.0  
6                           0.0  
8                           0.0  
10                          0.0  
11                          0.0  
...                         ...  
7044                        0.0  
7070                        0.0  
7080                        0.0  
7087                        0.0  
7105                        0.0  

[4081 rows x 10 columns]

In [64]:
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine,correlation

In [65]:
user_sim=1-pairwise_distances(user_movies_df.values,metric='cosine')

In [66]:
print(user_sim)

[[1.         0.         0.         ... 0.         0.         0.55337157]
 [0.         1.         0.         ... 0.45883147 0.         0.        ]
 [0.         0.         1.         ... 0.45883147 1.         0.62254302]
 ...
 [0.         0.45883147 0.45883147 ... 1.         0.45883147 0.47607054]
 [0.         0.         1.         ... 0.45883147 1.         0.62254302]
 [0.55337157 0.         0.62254302 ... 0.47607054 0.62254302 1.        ]]


In [67]:
user_sim_df=pd.DataFrame(user_sim)
user_sim_df.head()

0     1     2     3     4         5         6         7     8         9     \
0   1.0   0.0   0.0   0.0   1.0  0.000000  0.000000  0.000000   0.0  0.000000   
1   0.0   1.0   0.0   0.0   0.0  0.390567  0.707107  0.615457   0.0  0.000000   
2   0.0   0.0   1.0   0.0   0.0  0.650945  0.000000  0.492366   1.0  0.874157   
3   0.0   0.0   0.0   1.0   0.0  0.000000  0.000000  0.615457   0.0  0.388514   
4   1.0   0.0   0.0   0.0   1.0  0.000000  0.000000  0.000000   0.0  0.000000   

   ...  4071  4072  4073      4074      4075  4076      4077      4078  4079  \
0  ...   0.0   0.0   1.0  0.707107  0.000000   0.0  0.000000  0.000000   0.0   
1  ...   0.0   0.0   0.0  0.000000  0.000000   0.0  0.000000  0.458831   0.0   
2  ...   0.0   1.0   0.0  0.707107  0.000000   0.0  0.752577  0.458831   1.0   
3  ...   0.8   0.0   0.0  0.000000  0.989949   0.0  0.000000  0.619422   0.0   
4  ...   0.0   0.0   1.0  0.707107  0.000000   0.0  0.000000  0.000000   0.0   

       4080  
0  0.553372  
1  0.000000  
2  0.622543  
3  0.000000  
4  0.553372  

[5 rows x 4081 columns]

In [68]:
user_sim_df.index=movies_df.userId.unique()
user_sim_df.columns=movies_df.userId.unique()

In [69]:
user_sim_df.iloc[0:5,0:5]

3    6    8    10   11
3   1.0  0.0  0.0  0.0  1.0
6   0.0  1.0  0.0  0.0  0.0
8   0.0  0.0  1.0  0.0  0.0
10  0.0  0.0  0.0  1.0  0.0
11  1.0  0.0  0.0  0.0  1.0

In [70]:
user_sim_df.idxmax(axis=1)[0:5]

3      3
6      6
8      8
10    10
11     3
dtype: int64